### ISSUE TITLE
need support to ingest b3 headers for traces propagation from RabbitMQ

### ISSUE THREAD

**Issue by ddanishkhan** [signalfx/splunk-otel-java#1088]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/rabbitmq-2.7
I need the above instrumentation in the splunk-otel-java jar. 

Since I can't send traces through OTEL jar with below environment variables
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_ACCESS_TOKEN
          value: xyz
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: https://ingest.us0.signalfx.com
        - name: OTEL_EXPORTER_OTLP_REALM
          value: us0

**Comment by mateuszrzeszutek** [comment]
Hey @ddanishkhan ,
The instrumentation you linked is already present in the Splunk javaagent distro.

> - name: OTEL_EXPORTER_OTLP_ACCESS_TOKEN
> - name: OTEL_EXPORTER_OTLP_REALM

These two env var names are not correct; the ones we support are named `SPLUNK_ACCESS_TOKEN` and `SPLUNK_REALM` (see our [docs](https://docs.splunk.com/Observability/gdi/get-data-in/application/java/configuration/advanced-java-otel-configuration.html#general-settings) for more information).

**Comment by ddanishkhan** [comment]
Yes, I am using those with the Splunk Jar. 
My concern is regarding trace propagation via RabbitMQ messages with b3multi headers not working as expected. A new traceid is being created instead of using the existing one. 
I couldn't find this issue in the Splunk Doc anywhere

**Comment by mateuszrzeszutek** [comment]
I see. In general, unless you're using polling APIs (`basicGet`) this should work out of the box.
Please contact your sales rep about it, and have them open a support ticket -- we'll require more information about your use case (most likely see your application's code) to help you.

**Comment by breedx-splk** [comment]
Closing this as stale. If additional support is needed @ddanishkhan please reopen.
