### ISSUE TITLE
Failed to send metrics: Unable to send datapoints

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-java#1247]
I have updated Splunk helm  from v0.72.0 to v0.75.0 and getting flood of warning messages mentioned below. I have not updated the Java SDK. Please help.

[otel.javaagent 2023-04-25 22:23:30:008 +0000] [signalfx-metrics-publisher] WARN com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry - failed to send metrics: Unable to send datapoints

Env: AKS
Splunk Helm: v0.75.0
Splunk Otel JAVA SDK: 1.17

**Comment by mateuszrzeszutek** [comment]
@signalfx/gdi-data-collection-maintainers can you perhaps take a look at that? Is there anything in the latest release that might've impacted this? (auto-instrumentation, javaagent configuration, etc)

**Comment by breedx-splk** [comment]
@kumachop2 It's been a bit, did you get this resolved?

**Comment by kumachop2** [comment]
@breedx-splk I haven't got chance to research due to other priorities. Will check and revert shortly.

**Comment by mateuszrzeszutek** [comment]
I'm closing this issue; please reopen it or open a new one if you're still seeing these errors.
