### ISSUE TITLE
Vulnerability in jackson-core 2.14.x

### ISSUE THREAD

**Issue by jasonjckn** [signalfx/splunk-otel-java#1258]
com.fasterxml.jackson.core_jackson-core | 2.14.2  is vulnerable to CVE | PRISMA-2023-0067 , please upgrade to 2.15.x

**Comment by mateuszrzeszutek** [comment]
Hey @jasonjckn ,

Thanks for letting us know. We're planning to release the 1.24.0 release this week, it's going to include a fix for that too.

**Comment by jasonjckn** [comment]
thank you @mateuszrzeszutek
