### ISSUE TITLE
Use otel-collector-contrib image in Windows smoke tests

### ISSUE THREAD

**Issue by mateuszrzeszutek** [signalfx/splunk-otel-java#137]
And enable micrometer metrics for windows smoke tests.

But first, this PR: https://github.com/open-telemetry/opentelemetry-collector/pull/2272 needs to be ported to otel-collector-contrib repo.

**Comment by iNikem** [comment]
Why contrib?

**Comment by mateuszrzeszutek** [comment]
For signalfx metrics receiver, the "vanilla" otel-collector doesn't have it.
