### ISSUE TITLE
Instrumentation name and version tags listed twice

### ISSUE THREAD

**Issue by flands** [signalfx/splunk-otel-java#14]
One prefixed with `otel` and the other with `splunk`.

**Comment by iNikem** [comment]
InstrumentationLibrary information is carried and preserved as follows:

- OTLP protocol has it as a separate field and it is always present
- Zipkin and Jaeger exporters in Otel Java translate it into span attributes
- Latest released Otel Collector preserves incoming zipkin/jaeger `instrumentation_library` attributes when exporting to zipking/jaeger
- When receiving OTLP and exporting jaeger/zipkin, latest Otel Collector translates InstrumentationLibrary into span attributes.

Thus, at last, if latest Otel Java SDK and Collector are used, then InstrumentationLibrary is properly preserved on all paths. And we can now remove our custom `splunk` attributes.
