### ISSUE TITLE
Why are Spring built-in metrics not exported?

### ISSUE THREAD

**Issue by chenlujjj** [signalfx/splunk-otel-java#1596]
Hi team,

I tried to use this instrumentation agent with a simple Spring boot web application,  but found that the Spring built-in metrics were not exported.

## Spring service setup
`application.properties`:
```
server.port=8081

management.endpoint.health.group.custom.include=diskSpace,ping
management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always

management.endpoints.web.exposure.include=*
```

`build.gradle`:
```
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.0'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	// add prometheus registry
	implementation 'io.micrometer:micrometer-registry-prometheus:1.12.1'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

```

splunk-otel-java agent version:
I downloaded the agent via
```
curl -L https://github.com/signalfx/splunk-otel-java/releases/latest/download/splunk-otel-javaagent.jar \
-o splunk-otel-javaagent.jar
```
I think it's version 1.30

environment variables:
```
OTEL_SERVICE_NAME=demo;SPLUNK_METRICS_ENABLED=true;SPLUNK_METRICS_ENDPOINT=http://localhost:9943
```

NOTE：I ran a splunk-otel-collector in my local environment with a signalfx receiver and signalfx exporter.

## Output
From `http://localhost:8081/actuator/metrics` I can see many metrics like:
```
{
"names": [
"application.ready.time",
"application.started.time",
"demo.increase.called",
"demo.timer",
"disk.free",
"disk.total",
"executor.active",
"executor.completed",
"executor.pool.core",
"executor.pool.max",
"executor.pool.size",
"executor.queue.remaining",
"executor.queued",
"http.server.requests",
"http.server.requests.active",
"jvm.buffer.count",
"jvm.buffer.memory.used",
"jvm.buffer.total.capacity",
"jvm.classes.loaded",
"jvm.classes.unloaded",
"jvm.compilation.time",
"jvm.gc.live.data.size",
"jvm.gc.max.data.size",
"jvm.gc.memory.allocated",
"jvm.gc.memory.promoted",
"jvm.gc.overhead",
"jvm.gc.pause",
"jvm.info",
"jvm.memory.committed",
"jvm.memory.max",
"jvm.memory.usage.after.gc",
"jvm.memory.used",
"jvm.threads.daemon",
"jvm.threads.live",
"jvm.threads.peak",
"jvm.threads.started",
"jvm.threads.states",
"logback.events",
"process.cpu.usage",
"process.files.max",
"process.files.open",
"process.start.time",
"process.uptime",
"system.cpu.count",
"system.cpu.usage",
"system.load.average.1m",
"tomcat.sessions.active.current",
"tomcat.sessions.active.max",
"tomcat.sessions.alive.max",
"tomcat.sessions.created",
"tomcat.sessions.expired",
"tomcat.sessions.rejected"
]
}
```
Most of them are Spring built-in metrics, only two of them are my custom defined metrics:`"demo.increase.called","demo.timer"`.

But when I searched in SignalFx, I cannot find the Spring built-in metrics such as `http.server.requests`. However, the custom metrics can be found.

## Other thoughts

I found a PR that may be related to this case: https://github.com/signalfx/splunk-otel-java/pull/861.
But even I added env vars including:
```
OTEL_INSTRUMENTATION_MICROMETER_ENABLED=true;OTEL_INSTRUMENTATION_SPRING_BOOT_ACTUATOR_AUTOCONFIGURE_ENABLED=true;OTEL_INSTRUMENTATION_SPRING_CORE_ENABLED=true;OTEL_INSTRUMENTATION_SPRING_INTEGRATION_ENABLED=true;OTEL_INSTRUMENTATION_SPRING_WEB_ENABLED=true;OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED=true
```
the results remained the same.

Can someone help to look into this? How should I export the Spring metrics? 
Thanks in advance!

**Comment by laurit** [comment]
The spring boot actuator instrumentation from upstream does not work with with splunk-otel-java because it sends actuator metrics as otel metrics but splunk-otel-java uses micrometer for metrics (this will change in splunk-otel-java 2.0 where we'll switch to otel metrics). Similarly the upstream instrumentation for micrometer does not work with splunk-otel-java, we have a different instrumentation for the same purpose. So you shouldn't enable these instrumentation they won't help.
I believe what you need to do is to convince spring to send the metrics to the global micrometer registry that splunk-otel-java registers. For example see https://github.com/signalfx/splunk-otel-java/issues/1456#issuecomment-1743186905 Let us know whether you can make it work this way.

**Comment by chenlujjj** [comment]
Thanks @laurit I'll try the example later.

I still have some questions:

> The spring boot actuator instrumentation from upstream does not work with with splunk-otel-java because it sends actuator metrics as otel metrics but splunk-otel-java uses micrometer for metrics

But from the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics), "Spring Boot Actuator provides dependency management and auto-configuration for [Micrometer](https://micrometer.io/)"

> what you need to do is to convince spring to send the metrics to the global micrometer registry that splunk-otel-java registers

I thought spring uses the global micrometer registry too, here the [doc](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.getting-started) says: "Spring Boot also adds any auto-configured registries to the global static composite registry on the Metrics class, unless you explicitly tell it not to:"

**Comment by chenlujjj** [comment]
> Similarly the upstream instrumentation for micrometer does not work with splunk-otel-java, we have a different instrumentation for the same purpose

Take the `http.server.requests` as an example, does the splunk-otel-java provide metrics for the same purpose? I failed to find that in https://docs.splunk.com/observability/en/gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.html

**Comment by laurit** [comment]
> I thought spring uses the global micrometer registry too, here the [doc](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.getting-started) says: "Spring Boot also adds any auto-configured registries to the global static composite registry on the Metrics class, unless you explicitly tell it not to:"

https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.customizing says:


> By default, all MeterFilter beans are automatically bound to the Spring-managed MeterRegistry. Make sure to register your metrics by using the Spring-managed MeterRegistry and not any of the static methods on Metrics. These use the global registry that is not Spring-managed.

I would start by defining a `MeterRegistry` bean that returns the `MeterRegistry` used by the agent.

> Take the http.server.requests as an example, does the splunk-otel-java provide metrics for the same purpose?

Currently it does not. In version 2 we'll switch to otel metrics https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#http-server

**Comment by chenlujjj** [comment]
> what you need to do is to convince spring to send the metrics to the global micrometer registry that splunk-otel-java registers

Sry I'm a bit confused here, did you refer to the `io.micrometer.core.instrument.Metrics.globalRegistry` when you said "the global micrometer registry"? Actually I was using it to define my custom metrics like:
```
private val timer = Metrics.timer("o11y.test.timer")
```
and I could find the metrics in `/actuator/metrics` or `/actuator/prometheus` endpoint and signalfx as well

**Comment by laurit** [comment]
Yes, the registry that agent uses is added to `io.micrometer.core.instrument.Metrics.globalRegistry`. I believe the one that spring uses is also added there. `Metrics.timer("o11y.test.timer")` underneath uses the global registry so this metric will appear both in spring metrics endpoint and in the metrics exported by the agent.

**Comment by laurit** [comment]
Please reopen if you have more questions.
