### ISSUE TITLE
Change thread.id to String to match semconv

### ISSUE THREAD

**Issue by breedx-splk** [signalfx/splunk-otel-java#1754]
There is a breaking change in the works in upstream semconv to change `thread.id` from an integer to a String: https://github.com/open-telemetry/semantic-conventions/pull/836

We currently also have it defined as an integer here:
https://github.com/signalfx/splunk-otel-java/blob/main/profiler/src/main/java/com/splunk/opentelemetry/profiler/ProfilingSemanticAttributes.java#L43

We should take care with this, but we should also change our implementation to match the semconv. Bonus points if we can use a constant value from upstream instead of defining our own.

**Comment by laurit** [comment]
I think this issue can be closed, profiling attributes are not the same as otel semconv. The type of `thread.id` is defined as `int64` in https://github.com/signalfx/gdi-specification/blob/main/specification/semantic_conventions.md#pprof-profileproto-data-format

**Comment by breedx-splk** [comment]
ok
