### ISSUE TITLE
Examples links in README are stale

### ISSUE THREAD

**Issue by pmcollins** [signalfx/splunk-otel-java#2016]
Hello! The "examples" links in the readme point to https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing/opentelemetry-java-tracing which doesn't exist anymore. Perhaps the links should go to https://github.com/open-telemetry/opentelemetry-java-examples.

**Comment by breedx-splk** [comment]
Yeah, good catch @pmcollins. I agree and will update.

**Comment by breedx-splk** [comment]
Fixed in #2017 (I mistyped the issue there)
