### ISSUE TITLE
deployment.environment not honored in traces

### ISSUE THREAD

**Issue by hseljenes** [signalfx/splunk-otel-java#204]
https://github.com/signalfx/splunk-otel-java/pull/139 suggested a switch from `environment` to `deployment.environment` in the OTEL resources attributes but when I try that my environment is unset until it hits the Smart Agent which has a default environment set.

Should we use using both `environment` for traces and `deployment.environment` only for the new metrics exporter?

My env var looks like this
`OTEL_RESOURCE_ATTRIBUTES=service.name=MYSERVICE,deployment.environment=dev`

The ingested trace has these Tags

`deployment.environment=dev`
`environment=preprod`

Where `preprod` is the default environment set by our Smart Agent.

**Comment by hseljenes** [comment]
Ah, I'm guessing the Smart Agent isn't aware of the `deployment.environment` preference and since we set a default of `environment` that one takes preference in the Sfx app.

This issue can be closed if there's nothing to do at this time. We're going to go back to using just `environment` for now.

**Comment by flands** [comment]
Hey -- so `environment` is what SFx used prior to OTel semantic conventions existing. Now with OTel, `deployment.environment` is the recommendation. Splunk APM supports both and normalizes them -- `deployment.environment`. If you set each in a different location (instrumentation and data collection) then you can end up with two with different values. As I recall, `deployment.environment` wins.

In terms of your options here:
# Remove `environment` from Smart Agent config
# Update Smart Agent config to set `deployment.environment` instead
# Go back to `environment` in Java config

**Comment by hseljenes** [comment]
Thanks @flands! One of our infrastructure teams manages the Smart Agent so not sure when that will be able to be updated. We went back to using `environment` for the time being.
