### ISSUE TITLE
Broken pipe (write failed) for JVM metrics

### ISSUE THREAD

**Issue by hseljenes** [signalfx/splunk-otel-java#206]
We're using the 0.10.0 release to send JVM metrics to SignalFx, but our logs are filled with this log error every 10s (our submit rate).

```
[opentelemetry.auto.trace 2021-04-16 12:55:50:821 +0000] [signalfx-metrics-publisher] INFO com.signalfx.shaded.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {}->http://10.5.167.103:9080:  Broken pipe (Write failed)
[opentelemetry.auto.trace 2021-04-16 12:55:50:822 +0000] [signalfx-metrics-publisher] INFO com.signalfx.shaded.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://10.5.167.103:9080
```

This is happening both from containers running on OpenShift 3.11 with a Smart Agent on the underlying node and on OpenStack VMs with a Smart Agent locally.

This message does NOT appear if we send directly to `ingest.<region>.signalfx.com`

splunk-0.10.0-otel-1.1.0
signalfx-agent-5.7.1-1.x86_64

The metrics themselves seem to make it to SignalFx so perhaps it has something to do with how the connection is cleaned up?

I've attached the debug log with scrubbed details but a non-scrubbed one can be provided privately if needed.
[otel-jvm-metrics-broken-pipe-stack.log](https://github.com/signalfx/splunk-otel-java/files/6325184/otel-jvm-metrics-broken-pipe-stack.log)

Should we try with the generic OTEL agent?

Any help trying to debug this would be appreciated!

**Comment by hseljenes** [comment]
Meant to add even at debug level the `signalfx-agent` doesn't show any errors sending these and the internal metrics show `sfxagent.datapoints_failed=0`.

**Comment by jkwatson** [comment]
I don't know much about the SmartAgent, nor the signalfx metrics library, but this looks to be harmless logging of reset connections and the resulting retries. Since everything seems to be working fine, would it be ok to just change the log level to WARN, and ignore the INFO logging?

**Comment by mateuszrzeszutek** [comment]
Hmm, it is somewhat concerning that it's happening every 10 seconds. And judging by the fact that our backend does not seem to have this problem it seems to be something in the signalfx-agent.

@hseljenes it would be great if you could try opentelemetry-collector-contrib or splunk-otel-collector - it's the first time I'm seeing this kind of error, but there may be something unique to your setup that's causing it. Or maybe it's just a weird bug in the agent.
