### ISSUE TITLE
Change splunk.profiler.recording.duration option's unit to milliseconds

### ISSUE THREAD

**Issue by iNikem** [signalfx/splunk-otel-java#267]
To be consistent with OpenTelemetry specification:

https://github.com/open-telemetry/opentelemetry-specification/blob/ccbfdd9020ba0d581aa5d880235302f8b0eb8669/specification/sdk-environment-variables.md#duration

**Comment by breedx-splk** [comment]
Sounds good.

**Comment by jkwatson** [comment]
Note: the otel autoconfigure code will also handle standard time-unit suffixes for this. I do agree that ms should be the default if no suffix is detected, though (which is also the default autoconfigure behavior).
