### ISSUE TITLE
[Question] Integration with "spring-cloud-sleuth"

### ISSUE THREAD

**Issue by metacubed** [signalfx/splunk-otel-java#317]
We use [`spring-cloud-sleuth`](https://github.com/spring-cloud/spring-cloud-sleuth) and [`spring-cloud-sleuth-otel`](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel) in our Spring Boot applications. So I have a few questions:

1. How does this library `splunk-otel-java` agent integrate with `spring-cloud-sleuth-otel`?
1. If we enable both in our application, can they work well together?
1. Will this cause some duplicate instrumentation and increase lag?

Alternatively, is there a way to configure `spring-cloud-sleuth-otel` to send data directly to a Splunk OTel collector, bypassing the Splunk agent completely? What data collection would we lose in that case?

**Comment by mateuszrzeszutek** [comment]
Hey @metacubed,

> * How does this library `splunk-otel-java` agent integrate with `spring-cloud-sleuth-otel`?
> * If we enable both in our application, can they work well together?
> * Will this cause some duplicate instrumentation and increase lag?

Unfortunately there's no integration between Spring Seluth and splunk-otel-java. Using both of them at the same time may (and probably will) cause span duplication, broken context propagation, etc.
Both of those configure their own OpenTelemetry SDK copy completely separately of each other, so you may run into some major inconsistencies while you use both at the same time.

> Alternatively, is there a way to configure `spring-cloud-sleuth-otel` to send data directly to a Splunk OTel collector, bypassing the Splunk agent completely?

I think that if you configure the [OTLP exporter](https://spring-cloud-incubator.github.io/spring-cloud-sleuth-otel/docs/current/reference/html/project-features.html#features-otel-otlp) and [propagators](https://spring-cloud-incubator.github.io/spring-cloud-sleuth-otel/docs/current/reference/html/project-features.html#features-context-propagation) exactly the same as they're configured in this project then you'll be able to make it work with Splunk OTel Collector and other Splunk-instrumented apps.

> What data collection would we lose in that case/

You can compare [OTel javaagent instrumentations](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md) (and some [Splunk-specific ones](https://github.com/signalfx/splunk-otel-java/blob/main/docs/supported-libraries.md) that we provide) against [Sleuth integrations](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-integration).

**Comment by metacubed** [comment]
Thanks @mateuszrzeszutek. Looks like we have a few options to explore.

**Comment by mateuszrzeszutek** [comment]
Glad I was able to help! I'll close this issue, but feel free to reopen it (or open another one) if you have any other questions or problems with that.
