### ISSUE TITLE
un-released memory at the OTEL instrumentation layer

### ISSUE THREAD

**Issue by cbackstrom-spl** [signalfx/splunk-otel-java#409]
Splunk team, we are just becoming aware of an issue with un-released memory at the OTEL instrumentation layer.  See the attachment for some detail.  I do not have the application name or version of OTEL agent in-use, but will share that once the engineering team gives me some feedback. Please advise if this is a known-issue or something you're aware of being patched in latest OTEL agent. Please see below image.

![image](https://user-images.githubusercontent.com/89154553/129940542-f470bacd-7d9e-44e1-aa9b-918b2cd92880.png)

**Comment by mateuszrzeszutek** [comment]
We had a memleak in netty instrumentation a couple months ago: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3294
I can't really confirm that this is what you're observing with this amount of information though - sharing the javaagent version, or the full class name from your screenshot, would hopefully make that clearer.

**Comment by brandoncurrie** [comment]
This was with version `splunk-1.0.0-otel-1.2.0` and several applications have updated to `splunk-1.2.0-otel-1.4.0` to see if the problem persists.

**Comment by mateuszrzeszutek** [comment]
Yes, the problem that I linked before was present in the otel 1.2.0 version. Upgrading might help - but still, with so little information I can't confirm with an absolute certainty that this memleak was the netty issue we've had.

**Comment by breedx-splk** [comment]
@cbackstrom-spl @brandoncurrie Any updates with the newer version (1.4.0 is current)?

**Comment by brandoncurrie** [comment]
Yes, thanks for the reminder. the memory leaks are no longer an issue after
upgrading to the newer versions of the agent.
