### ISSUE TITLE
Trace breaks at message subscriber boundary

### ISSUE THREAD

**Issue by bluetentacle** [signalfx/splunk-otel-java#550]
I'm finding each time a the Java agent receives a message from RabbitMQ or Kafka, a new trace is created.

Here's my set up:

![image](https://user-images.githubusercontent.com/1126817/143700270-a0f7f509-7986-44c2-ac50-b752d7928678.png)

The service `loan-adapter` subscribes to RabbitMQ `amq.topic`, but no connection is shown. The service `loan-logger` subscribes to the Kafka topic `loan`, but the correlation is also absent.

The other services are .NET services using the nextver agent, and the trace correctly connects all of them through the various protocols.

Please help.

**Comment by mateuszrzeszutek** [comment]
Hey @bluetentacle ,
1. Are you using any RabbitMQ wrapper library? Or the `amqp-client` directly? What are your usage patterns?
2. Regarding Kafka: can you try setting `-Dotel.instrumentation.common.experimental.suppress-messaging-receive-spans=true`? OTel messaging conventions suggest starting a separate trace for receiving/processing the message and using span links to correlate these two together - unfortunately our backend doesn't handle span links well yet; the configuration flag I mentioned reverts back to the "naive" parent-child producer-consumer relationship. (Also, it's probably worth mentioning that messaging semantic conventions are still being developed; it is possible that the current default behavior will be changed at some point in the future)

**Comment by bluetentacle** [comment]
Hi @mateuszrzeszutek. Thank you for your reply. That property setting worked out for Kafka. Now loan-logger is integrated into the trace: 

![image](https://user-images.githubusercontent.com/1126817/143926628-6251a98b-0ad7-4ed1-bd39-11de270ccb33.png)

RabbitMQ still does not work. I'm using spring-boot-starter-amqp to subscribe to messages. The publisher is a .NET Core service. Here're the message headers that loan-adapter receives. On the subscriber end, I set `OTEL_PROPAGATORS=tracecontext,baggage,b3multi,b3`

x-b3-parentspanid=06d1683afa6a8fb4
x-b3-traceid=149a0e3976b6596e47f90a75fa615947
x-b3-spanid=6e58de32e25e850b
x-b3-sampled=1

**Comment by mateuszrzeszutek** [comment]
Hmm, it is unexpected that this is not working (we even have some tests that cover [`@RabbitListener`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-rabbit-1.0/javaagent/src/test/groovy/ContextPropagationTest.groovy) in the upstream agent repo).

What java agent version are you using?
Does the .NET service that produces the message appear in the graph you posted?
Does the consumer span have a parent? (when you turn on either javaagent or collector debug logging)

**Comment by bluetentacle** [comment]
- Java agent is 1.5.0, downloaded from https://github.com/signalfx/splunk-otel-java/releases/latest/download/splunk-otel-javaagent-all.jar
- The .NET service that produced the rabbitmq message is lead-manager
- In loan-adapter, I'm logging the tracing headers in the received RabbitMQ message:

```
x-b3-parentspanid=06d1683afa6a8fb4
x-b3-traceid=149a0e3976b6596e47f90a75fa615947
x-b3-spanid=6e58de32e25e850b
x-b3-sampled=1
```

Do I need to turn on debug logging and what should I look for?

**Comment by mateuszrzeszutek** [comment]
Do the lead-manager spans and loan-adapter spans have different traceId?
You can also add the debug logging exporter in your collector config and check the logs if the CONSUMER span has any parent -- see [an example](https://github.com/signalfx/splunk-otel-java/blob/main/testing/profiler-tests/src/test/resources/collector.yaml#L36) from our tests:

```yaml
exporters:
  logging/logging_debug:
    loglevel: debug

# ...

service:
  pipelines:
    traces:
      # ...
      exporters: [ logging/logging_debug, ... ]
```

This should help us pinpoint whether this is an instrumentation or ingest issue.

**Comment by mateuszrzeszutek** [comment]
No, that's the config file for the https://github.com/signalfx/splunk-otel-collector (or https://github.com/open-telemetry/opentelemetry-collector/) that you're using.

**Comment by mateuszrzeszutek** [comment]
Hey @bluetentacle ,
Has you problem been solved? Do you need any more help with this?

**Comment by mateuszrzeszutek** [comment]
Hey @bluetentacle ,
I'm closing this issue -- if you're still struggling with these propagation issues with your setup please reopen/create a new one.
