### ISSUE TITLE
Profiler only logs collector connectivity issues as DEBUG

### ISSUE THREAD

**Issue by gsmirnov-splk** [signalfx/splunk-otel-java#566]
This came up in a customer troubleshooting session. No data was coming to the collector, but no errors were displayed in the agent logs. After debug logs were turned on via `-Dotel.javaagent.debug=true`, the problem became clear. As it turned out, the endpoint was specified as `https://localhost:4317` (note the protocol)

```
Caused by: io.grpc.netty.shaded.io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 000006040000000000000500004000
```

To make future troubleshooting faster, this sort of errors should be logged at the WARN level. To avoid polluting the logs too much, consider logging it just once per run or per hour. We should also very non-ambiguously mark the log messages as coming from the Splunk Java Agent, not from the instrumented application itself.

**Comment by breedx-splk** [comment]
We can implement this for the exporter in our repo, but it will be a short-term fix because we eventually be using all the logging components from upstream. At that point, this one-shot error logging would need to built into upstream.

The current guidance is always to turn on debug logging to troubleshoot such issues.

**Comment by gsmirnov-splk** [comment]
@breedx-splk where does this current guidance come from and what's the justification? Turning debug logs requires the customer to re-deploy the service, increasing time-to-value. And if agent shows no errors whatsoever, how do we even know we should troubleshoot it on the agent side? Well, *now* I know...

**Comment by breedx-splk** [comment]
@gsmirnov-splk The guidance is from the instrumentation team and the community. The justification? I dunno. Probably that customers often pay for logs and don't want it cluttered with agent information. It can also be unexpected/surprising for operations and o11y folks to see instrumentation logs intermixed with their application logs when troubleshooting. Thirdly, I guess that some applications rely on the stdout of other applications, and any output by default complicates this.

I agree that showing nothing makes it difficult when things go wrong.

**Comment by iNikem** [comment]
@gsmirnov-splk you may ask in https://github.com/open-telemetry/opentelemetry-java-instrumentation about "What is our guidelines about problem logging from agent?" I am not sure from the top of my head right now what we do with e.g. built-in exporters...

**Comment by gsmirnov-splk** [comment]
@breedx-splk @iNikem thanks! Asked it here too: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4886
