### ISSUE TITLE
opentelemetry-java-instrumentation released 1.9.2

### ISSUE THREAD

**Issue by sh777** [signalfx/splunk-otel-java#614]
Open telemetry released a patch for fixing a memory leak issue(https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.9.2). The issue could be reproduced in our latest version as well.

Can we do a patch to fix the same issue?

**Comment by mateuszrzeszutek** [comment]
Hey @sh777 ,
Is this and urgent issue for you? We're planning to make the 1.10.0 upstream release by the end of this week, and the 1.7.0 release of this distro a day later; it will include that fix too. Would it be possible for you to wait for that? Of course, if it's urgent for you we'll release the patch release right away.

**Comment by sh777** [comment]
Hey @mateuszrzeszutek,
We can wait for another few days. But we do worry about this issue or similar issue would reappear in the next release. As it happened several times before.  Then we will have to wait for another few weeks. However we do need a feature from this version urgently. Therefore to minimum the risk we will appreciate if you could help with a patch.

**Comment by mateuszrzeszutek** [comment]
Okay, got it. I'll work on that patch release then, you can expect it to happen today.

**Comment by mateuszrzeszutek** [comment]
Hey @sh777 ,
It looks like we're facing some Gradle Plugin Portal related issues in our builds (well, it's not just us, OpenTelemetry projects fail too...) - this will delay the patch release a bit, depending on how fast the Gradle team fixes this.

**Comment by sh777** [comment]
Well noted with thanks.

**Comment by mateuszrzeszutek** [comment]
Hey @sh777  -- we've released [v1.6.1](https://github.com/signalfx/splunk-otel-java/releases/tag/v1.6.1) with the reactor-netty fix.
