### ISSUE TITLE
Profiling Configuration log-at-startup is missing memory profiling

### ISSUE THREAD

**Issue by gsmirnov-splk** [signalfx/splunk-otel-java#623]
Running with `splunk-1.6.1-otel-1.9.2` with `-Dsplunk.memory.profiler.enabled=true`, I see this logged at startup:

```
ConfigurationLogger - -----------------------
ConfigurationLogger - Profiler configuration:
ConfigurationLogger -                 splunk.profiler.enabled : true
ConfigurationLogger -               splunk.profiler.directory : .
ConfigurationLogger -      splunk.profiler.recording.duration : 20s
ConfigurationLogger -              splunk.profiler.keep-files : false
ConfigurationLogger -           splunk.profiler.logs-endpoint : null
ConfigurationLogger -             otel.exporter.otlp.endpoint : http://collector:4317
ConfigurationLogger -            splunk.profiler.tlab.enabled : false
ConfigurationLogger -       splunk.profiler.period.threaddump : PT1S
ConfigurationLogger - -----------------------
```

No mention of memory profiling here. Also no mention of metrics being turned on. Perhaps this can be solved in a generic way? Just make sure that all the configs that the java agent looks at are logged? Without having to manually add every new item?

**Comment by breedx-splk** [comment]
The memory look like they are logged now. https://github.com/signalfx/splunk-otel-java/blob/main/profiler/src/main/java/com/splunk/opentelemetry/profiler/ConfigurationLogger.java#L54 
Please reopen if this is not the case. Thanks!
