### ISSUE TITLE
build.gradle replaced with build.gradle and class file for io.opentelemetry.api.trace.Span not found warning

### ISSUE THREAD

**Issue by sparam** [signalfx/splunk-otel-java#63]
Hi @iNikem ,

Would like to report 2 observation:

**1. build.gradle file**

Just curious to know why in version v0.4.0 build.gradle.kts got replaced with build.gradle? I had some code added to build.gradle.kts to publish to the maven repository.

https://github.com/signalfx/splunk-otel-java/commit/4d51b2b91bec29b7d2291ff145db623e3639e905

**2. Build shows below warning:**

```
> Task :matrix:compileJava
warning: unknown enum constant Kind.INTERNAL
  reason: class file for io.opentelemetry.api.trace.Span not found
1 warning

```

**Comment by iNikem** [comment]
Build file was converted from kotlin to groovy to follow examples from upstream repo: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/examples/distro .

I cannot explain the second thing right now (yes, I have seen it too) :)

**Comment by sparam** [comment]
got it. Did not notice those examples before. thanks for sharing. 

A different issue, please let me know if you want me to create a new issue.

I am using Java 8 and looks like test  expects >Java10. Can this be made backward compatible with Java 8?

```
> Task :custom:compileTestJava FAILED
/Users/sparam/Documents/githome/splunk-otel-java/paypal-splunk-otel-java-FORK/custom/src/test/java/com/splunk/opentelemetry/jaeger/AuthTokenInterceptorTest.java:44: error: cannot find symbol
    var request = new Request.Builder().url("http://test").build();
    ^
  symbol:   class var
  location: class AuthTokenInterceptorTest
1 error
```

**Comment by iNikem** [comment]
That I cannot promise you :) Both this repo and upstream OpenTelemetry Java instrumentation require Java 11 for building. Java 8 is still supported for running.

**Comment by iNikem** [comment]
@sparam Regarding compile time warning about `Kind.INTERNAL`: https://github.com/open-telemetry/opentelemetry-java/pull/2336#pullrequestreview-554399885

**Comment by sparam** [comment]
thanks @iNikem Is this a blocking change for Version 0.4.0? 

`compile time warning about Kind.INTERNAL`

**Comment by vovencij** [comment]
This warning shouldn't be breaking anything unless you use `@WithSpan` annotation in an environment, where the rest of the opentelemetry-java/instrumentation is missing. If you have an agent attached, then you have all the needed dependencies.

**Comment by iNikem** [comment]
@sparam Can we close this issue if all your questions were answered?

**Comment by sparam** [comment]
Hi @iNikem yes. I will close the ticket. Thanks for sharing the details.
