### ISSUE TITLE
need help: how to  convert the project to maven 

### ISSUE THREAD

**Issue by whispin** [signalfx/splunk-otel-java#701]
I am not familiar with gradle, can  provide a way to convert the project to maven ,or provider the pom.xml

**Comment by mateuszrzeszutek** [comment]
Hey @whispin ,
We have lots of custom build logic implemented in our gradle scripts, we're not going to replace it with maven. Besides, artifacts produced by gradle builds are 100% compatible with maven - you can find all the release artifacts on [sonatype](https://oss.sonatype.org/service/local/repositories/releases/content/com/splunk/splunk-otel-javaagent/1.8.2/).
