### ISSUE TITLE
Have separate Custom project which uses Splunk/Otel dependencies

### ISSUE THREAD

**Issue by sparam** [signalfx/splunk-otel-java#77]
@iNikem 
Currently we are using fork/mirroring https://github.com/signalfx/splunk-otel-java/ and adding custom code for propagation under custom directory https://github.com/signalfx/splunk-otel-java/tree/main/custom. The problem is, this requires on top of getting the recent versions of otel, we also have to pull in the code changes and java/gradle files (eg: filesunder https://github.com/signalfx/splunk-otel-java/tree/main/agent which as an end user we do not make any changes) done by Splunk on top of the Otel dependencies. we then do the build of splunk-otel-java to generate an agent library.

As an end-user, can we separate the custom code from the [splunk-distro](https://github.com/signalfx/splunk-otel-java)? Say the custom project will have only code that we are adding to support custom propagation (Eg: "endusercompanyname-custom-otel.jar") . This custom project at the time of build will pull the dependencies like Splunk/Otel libraries. So at the time of building the library, we do not need to mirror all the code that is written by Splunk and maintain it in the mirror. Instead we just pull in the dependencies. This will avoid the maintenance cost by not maintaining the files written by Splunk but have only a jars as dependencies.

**CustomProject:**
 gradle: pulls the splunk-otel-java jar (which has otel packaged within it)
 custom: add custom code

**Comment by iNikem** [comment]
So you want second derivative of Otel distribution? :) I think this can be done.

**Comment by sparam** [comment]
@iNikem could be second derivative. It will really avoid the enduser from pulling code written by the vendor and doing build with that code. Instead the enduser has a distro that will require only to add the needed custom code and maintain the code written by the end-user.

**Comment by iNikem** [comment]
Btw, @sparam , have you tried taking https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/examples/distro and just replacing https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/examples/distro/agent/build.gradle#L10 with coordinates for Splunk distribution? Although I haven't tried it yet, I wouldn't be surprised if this works out of the box :)

**Comment by sparam** [comment]
Hi @iNikem It is a good idea :) . I have to try it out. Is this something that Splunk could support along with the current distro as 2 approaches of using splunk java agent?

**Comment by iNikem** [comment]
We certainly cannot support your distribution :) And I am not sure I am in position to say something about Splunk support :) But as engineer to engineer, I think this agent repackaging to custom distro is here to stay.

**Comment by sparam** [comment]
Ack. Thanks!

**Comment by sparam** [comment]
Hi @iNikem I was looking at some examples https://github.com/open-telemetry/opentelemetry-java/blob/master/examples/grpc/src/main/java/io/opentelemetry/example/grpc/ExampleConfiguration.java. The code that is part of the distro example, like the [propagator configuration](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/examples/distro/custom/src/main/java/com/example/javaagent) seems to have been implemented as part of the application. If the custom propagator is added as part of application as per the example configuration, is it required that we add the custom propagator to custom folder in the distro?

**Comment by iNikem** [comment]
I am not sure i understand what do you mean by "part of the application"?

`opentelemetry-java` examples are all for application developers, because they are the main users of SDK, who have to configure SDK in a manner suitable for their application.

`opentelemetry-java-instrumentation` examples are for javagent developers/repackagers. And one of the responsibilities of javaagent is to configure SDK. So [this code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro/custom/src/main/java/com/example/javaagent) is definitely NOT part of the application :)

So if you want to configure SDK in (every) application, follow the examples of `opentelemetry-java` repository. If you want to have a javaagent, which provides SDK configuration automatically, then follow the examples of `opentelemetry-java-instrumention` repository.

**Comment by sparam** [comment]
okay. thanks for the clarification.

**Comment by iNikem** [comment]
@sparam Does this task need any more action or can I close it?

**Comment by sparam** [comment]
this can be closed. I am yet to look into creating distro from example; will try it when I get to it :). Thanks @iNikem
