### ISSUE TITLE
Bring JaegerThrift exporter and factory into this repo

### ISSUE THREAD

**Issue by breedx-splk** [signalfx/splunk-otel-java#85]
For good reason, the upstream agent is looking to remove the `JaegerThriftSpanExporter` (and supporting factory/builders).  Splunk should probably get ahead of this upstream issue:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1973
and copy the classes into this repo so that they can be removed there.

**Comment by breedx-splk** [comment]
We didn't get ahead of it.  :). Anyway, here's the PR that removed it: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2073

**Comment by mateuszrzeszutek** [comment]
Hmm, isn't it already here? https://github.com/signalfx/splunk-otel-java/blob/main/custom/src/main/java/com/splunk/opentelemetry/jaeger/JaegerThriftSpanExporterFactory.java

It was added to this repo before otel-java-instr had it

**Comment by breedx-splk** [comment]
Ok, the factory is here but the `JaegerThriftSpanExporter` is not (yet).  The factory imports it from upstream (I think).

**Comment by jkwatson** [comment]
`JaegerThriftSpanExporter` is in the main java repo: https://github.com/open-telemetry/opentelemetry-java/tree/master/exporters/jaeger-thrift

**Comment by breedx-splk** [comment]
Aha!  Then I think we are good.  Thanks y'all.
