### ISSUE TITLE
otel java agent should append Server-Timing to Access-Control-Expose-Headers if it already exists

### ISSUE THREAD

**Issue by mypchas6fans** [signalfx/splunk-otel-java#870]
Our java service sets response header Access-Control-Expose-Headers to "content-disposition" for our own usage.

After leaving SignalFX, the value becomes "Server-Timing", which should be "Server-Timing,content-disposition"

Currently we are using splunk-otel-javaagent 1.7.0
But the main branch here seems share the same behavior:

https://github.com/signalfx/splunk-otel-java/blob/2fe90534a85947e8f01e5cbb5218124034e9a07a/instrumentation/common/src/main/java/com/splunk/opentelemetry/instrumentation/servertiming/ServerTimingHeader.java#L38

**Comment by mateuszrzeszutek** [comment]
Hey @mypchas6fans ,
Thanks for filing this issue! This looks like a bug; we'll fix this in the upcoming release.

**Comment by laurit** [comment]
@mypchas6fans could you try with 1.9.0 or later, we believe that this might have already been fixed

**Comment by mypchas6fans** [comment]
Yes we tested 1.9.1 and the header value is only "content-disposition".
Thanks for clarification.

**Comment by michal-filip** [comment]
It looks like we can reproduce this on `splunk-1.17.0-otel-1.19.1`. Our custom header name is `total-count` and instead of the two values being combined, the Server-Timing one ends up being the only one in the response.

**Comment by mateuszrzeszutek** [comment]
Hey @michal-filip ,
Can you share some more details of your setup? Are you using servlets, or netty (or something that uses one of these internally, e.g. spring)? What version of the library?

**Comment by breedx-splk** [comment]
Please reopen if still an issue.
