### ISSUE TITLE
Spring batch spans

### ISSUE THREAD

**Issue by sparam** [signalfx/splunk-otel-java#90]
Hi,

I used https://github.com/spring-guides/gs-batch-processing (https://spring.io/guides/gs/batch-processing) application to test the Spring batch instrumentation support https://github.com/signalfx/splunk-otel-java/pull/88. I am seeing spans for the jdbc, but not for Spring batch. Any thoughts?

otel.library.name | io.opentelemetry.javaagent.jdbc

**Comment by vovencij** [comment]
`spring-batch` instrumentation seems to be disabled by default. Can you try adding this jvm argument: `-Dotel.instrumentation.spring-batch.enabled=true`

**Comment by mateuszrzeszutek** [comment]
What version of `splunk-otel-java` are you using? Starting from v0.6.0 spring batch instrumentation is enabled by default; in earlier versions you had to manually enable it.

**Comment by vovencij** [comment]
Sorry, my bad, was using a build before 0.6.0 and saw in the logs that it is disabled. With 0.6.0 it is indeed enabled by default.

**Comment by sparam** [comment]
Hi @vovencij @mateuszrzeszutek  I am using 0.6.0

```
telemetry.auto.version | splunk-0.6.0-otel-0.14.0
telemetry.sdk.language | java
telemetry.sdk.name | opentelemetry
telemetry.sdk.version | 0.14.1
opencensus.exporterversion | Jaeger-opentelemetry-java
```

Not sure the version of spring batch of the [spring application](https://spring.io/guides/gs/batch-processing) i am using could be the reason for no batch spans.

**Comment by mateuszrzeszutek** [comment]
Hey @sparam,

I've run the example app and noticed that it quits immediately after the job is finished - spans are exported/sent in a daemon thread which might just get killed before it actually does anything.
I've added a small delay to the main function (`Thread.sleep(2000)`) and I could see all the Spring Batch spans after that:

```
... 'BatchJob importUserJob.step1.Chunk' : d9457ba0f50cf89ad42ec5886aadc736 14f9c837f3cf5dfa thread.id=1 thread.name="main"
... 'BatchJob importUserJob.step1' : d9457ba0f50cf89ad42ec5886aadc736 cc3a28e90ed7f80f thread.id=1 thread.name="main"
... 'BatchJob importUserJob' : d9457ba0f50cf89ad42ec5886aadc736 6bc1f01652eb2e5e thread.id=1 thread.name="main"
```

**Comment by sparam** [comment]
thanks @mateuszrzeszutek I am seeing the batch spans after setting the wait time to 12 seconds. Would this be a concern with short running batch jobs?

**Comment by mateuszrzeszutek** [comment]
> Would this be a concern with short running batch jobs?

It depends: if the application/process ends together with the batch job then yes, you can lose some data. But if you have an application that runs continuously and starts batch jobs e.g. based on cron/timer then this won't be a problem.

>  before the daemon started there were some spans that did not get captured by the daemon

The exporter daemon thread starts before any span is registered, so this should not be a problem.

Right now you can only lose some spans when the application finishes too soon, but this will soon stop being a problem: the newest OpenTelemetry SDK already adds a shutdown hook that closes the `TracerProvider`, so this issue will disappear in the next agent version.

**Comment by sparam** [comment]
thanks! just a thought: would it be possible to have a shutdown hook that gets triggered, which sends out the remaining spans once the application shuts down.

**Comment by iNikem** [comment]
@sparam I believe this is exactly what @mateuszrzeszutek said :) :

> the newest OpenTelemetry SDK already adds a shutdown hook that closes the TracerProvider

**Comment by sparam** [comment]
My bad. Did not realize that the comment was applicable to both the questions. Thanks for clarifying and providing a solution. Thanks @mateuszrzeszutek @iNikem . 

This issue can be marked as closed.
