### ISSUE TITLE
404 on using ingest endpoints

### ISSUE THREAD

**Issue by milindsingh** [signalfx/splunk-otel-java#912]
I have provided the below env variables, still the agent gives a 404 error.

```
ENV SPLUNK_ACCESS_TOKEN=<access-token>
ENV SPLUNK_REALM=jp0
```

```
[OkHttp https://ingest.jp0.signalfx.com/...] WARN io.opentelemetry.exporter.internal.grpc.OkHttpGrp
cExporter - Failed to export logs. Server responded with HTTP status code 404. Error message: Not Found
```

**Comment by breedx-splk** [comment]
Hi @milindsingh. Are you still experiencing this problem? If so, would it be possible for you to provide some additional information about your configuration? Are you using a proxy or a firewall? Does this happen for every request, or just during certain times/dates? Anything else to go on?

**Comment by milindsingh** [comment]
Its happening for every request. I am beside Zscaler, but that would not result in 404.

How can I see more details logs while profiler enabled?

**Comment by breedx-splk** [comment]
Oh ok, I think I'm understanding a bit more about your situation now. You're trying to use profiling, which leverages logs, and you are using the `SPLUNK_REALM` advanced configuration item to tell the agent where to send its telemetry. Unfortunately, [profiling requires the use of a collector](https://github.com/signalfx/splunk-otel-java/tree/main/profiler#requirements) and "direct ingest" is not yet supported for profiling data.

The docs for `splunk.realm` don't really use the term "direct ingest", so I understand why this might be confusing.

Your best bet is to run the Splunk distribution of the OpenTelemetry Collector. If it's on the same host (localhost) then you don't need to configure the agent really at all. If it's on a different host, you can configure `OTEL_EXPORTER_OTLP_ENDPOINT` to tell the agent where the collector lives.

Does that help? 

Thanks for bringing this to our attention. I think we need to adjust something in the case where profiling and `SPLUNK_ENDPOINT` are both used...at least we should log a warning/error.

**Comment by milindsingh** [comment]
@breedx-splk Thanks for clarification, I have removed the profiler env variable. I am trying to push my Java app logs to SignalFX Log Observer.

The below `Dockerfile` is used to test the integration. Any suggestion on what missing ? 

```bash
ARG JAVA_VERSION=11
# This image additionally contains function core tools – useful when using custom extensions
#FROM mcr.microsoft.com/azure-functions/java:4.0-java$JAVA_VERSION-core-tools AS installer-env
FROM mcr.microsoft.com/azure-functions/java:4.0-java$JAVA_VERSION-build AS installer-env

# Zscaler certificate import for ssl verification on local network
COPY ./certs /src/certs
RUN keytool -import  -trustcacerts -cacerts -storepass changeit -noprompt -alias zscalerrootca -file /src/certs/ZscalerRootCertificate-2048-SHA256.der

COPY . /src/java-function-app
RUN cd /src/java-function-app && \
    mkdir -p /home/site/wwwroot && \
    mvn clean package && \
    cd ./target/azure-functions/ && \
    cd $(ls -d */|head -n 1) && \
    cp -a . /home/site/wwwroot

# Splunk agent download and add
RUN curl --insecure -L https://github.com/signalfx/splunk-otel-java/releases/latest/download/splunk-otel-javaagent.jar \
-o splunk-otel-javaagent.jar
RUN mkdir -p /home/site/wwwroot/splunk
RUN mv ./splunk-otel-javaagent.jar /home/site/wwwroot/splunk/splunk-otel-javaagent.jar


# This image is ssh enabled
FROM mcr.microsoft.com/azure-functions/java:4.0-java$JAVA_VERSION-appservice
# This image isn't ssh enabled
#FROM mcr.microsoft.com/azure-functions/java:4.0-java$JAVA_VERSION

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]

# Zscaler certificate import for ssl verification on local network
COPY ./certs /src/certs
RUN /usr/lib/jvm/zre-11-azure-amd64/bin/keytool -import  -trustcacerts -cacerts -storepass changeit -noprompt -alias zscalerrootca -file /src/certs/ZscalerRootCertificate-2048-SHA256.der

# Splunk agent setup
ENV OTEL_SERVICE_NAME=my-service-dev

ENV SPLUNK_ACCESS_TOKEN=<token>
ENV SPLUNK_REALM=eu0

ENV SPLUNK_METRICS_ENABLED=false
ENV JAVA_OPTS="$JAVA_OPTS -javaagent:/home/site/wwwroot/splunk/splunk-otel-javaagent.jar"
```

**Comment by breedx-splk** [comment]
Thanks @milindsingh. This is starting to get a little off-topic for our instrumentation agent, but let's make sure that we are on the same page. 

I'm pretty sure Log Observer ingest requires HEC format logs, which our agent here cannot export directly. The common/expected use case is to either send logs to an otel collector or use one of the collector integrations to scrape the logs from another place. The collector can then use a HEC exporter to send logs to Splunk Log Observer ingest.

I don't know enough about your deployment environment to really make any more specific suggestions, but there are [some additional suggestions in the docs](https://docs.splunk.com/Observability/logs/logs.html#nav-Set-up-Log-Observer).

**Comment by breedx-splk** [comment]
@milindsingh Do you want to keep this issue open and chat more about this? If not, we'd prefer to close it so this issue doesn't go stale. Thanks.

**Comment by breedx-splk** [comment]
@milindsingh Please reopen if this is still a concern. Thanks!
