### ISSUE TITLE
any improve to make these tags be optional?

### ISSUE THREAD

**Issue by Shawn-Yang-AWX** [signalfx/splunk-otel-java#922]
any improve to make these tags be optional? or how can i disable these tags
```
addTag(globalTags, PROCESS_PID.getKey(), PROCESS_PID);
```

if the process id change, the metrics records maybe double, and you know, the cost base on the metrics records

**Comment by mateuszrzeszutek** [comment]
Hey @Shawn-Yang-AWX ,
You could configure your [collector](https://github.com/signalfx/splunk-otel-collector) instance to drop that attribute for received metrics; see the [attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) documentation for lots of detailed examples on how to configure it. Once you configure attribute removing processor, you can add it to the metrics pipeline, for example like in [here](https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/config/collector/agent_config.yaml#L170).

**Comment by Shawn-Yang-AWX** [comment]
good, thanks.
