### ISSUE TITLE
Missing traceIds in logs for SQS calls

### ISSUE THREAD

**Issue by apoorva88** [signalfx/splunk-otel-java#933]
WE are not seeing the trace ids in logs for SQS calls although we see it in the APM.
we get traceId=NO_TRACE_RUNNING in these scenarios
We are using version 1.9 of Splunk java agent

**Comment by mateuszrzeszutek** [comment]
Hey @apoorva88 ,
We'll need a bit more details about your case. Can you perhaps contact the sales representative and have them create a support case for you? We'll need to know what javaagent, JVM versions you're using; what logging library and which version; a code example/fragment that shows how you're using SQS and the log framework; and ideally the javaagent debug logs (`-Dotel.javaagent.debug=true`).
Thanks!

**Comment by breedx-splk** [comment]
Hi @apoorva88. Is this still an issue for you? Can you reply to @mateuszrzeszutek's items above please. We'll close this issue as stale next week if we don't hear back (you can always reopen). Thanks!

**Comment by breedx-splk** [comment]
Ok, please reopen if still relevant. Thanks.
