### ISSUE TITLE
jackson-databind is getting older version than latest

### ISSUE THREAD

**Issue by psumu** [signalfx/splunk-otel-java#945]
Hi Team, 

We are using the latest version of otel java agent jar(v1.16.0) and could see it's bringing 2.13.3 version of jackson-databind whcih has some high vulnerabilities showing from gcrype anchor scan.
Please find the vulnerabilities details below in details.
NAME              INSTALLED  FIXED-IN    TYPE          VULNERABILITY        SEVERITY 
jackson-databind  2.13.3     2.14.0-rc1  java-archive  GHSA-jjjh-jjxp-wpff  High      
jackson-databind  2.13.3     2.13.4      java-archive  GHSA-rgv9-q543-rqg4  High  

Please let us know, is ther any plan to address above vulnerabilities  in upcmong release?

**Comment by mateuszrzeszutek** [comment]
Hey @psumu ,
The 1.17 release will most likely happen at the end of this week or early next week, and it will contain the 2.13.4 version of jackson. We'll bump jackson to 2.14 once a stable release is available.
